[workspace]
channels = ["conda-forge"]
name = "strudel"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]
build = "pnpm install"
test = "pnpm start"

[dependencies]
pnpm = ">=10.15.1,<11"
nodejs = ">=22.17.1,<22.18"
